In [1]:
import sys
import os
from pathlib import Path

sys.path.append(str(Path.cwd().parents[0]))

%load_ext autoreload
%autoreload 2

In [10]:
from experiments.analysis import get_results

df_loss_s1 = get_results("../results/cv/loss", "s1")
df_loss_s1

,name,overall_accuracy,overall_balanced_accuracy,stable_accuracy,stable_balanced_accuracy,converter_accuracy,converter_balanced_accuracy
0,s1_severity_100,0.8758 ± 0.0221,0.8721 ± 0.0204,0.9160 ± 0.0225,0.9096 ± 0.0224,0.5894 ± 0.0243,0.5580 ± 0.0491
1,s1_severity_000,0.8741 ± 0.0238,0.8693 ± 0.0225,0.9128 ± 0.0229,0.9056 ± 0.0226,0.5987 ± 0.0381,0.5732 ± 0.0523
2,s1_severity_025,0.8699 ± 0.0235,0.8679 ± 0.0211,0.9084 ± 0.0251,0.9036 ± 0.0243,0.5955 ± 0.0293,0.5641 ± 0.0490
3,s1_severity_075,0.8697 ± 0.0270,0.8671 ± 0.0249,0.9085 ± 0.0273,0.9023 ± 0.0256,0.5936 ± 0.0312,0.5738 ± 0.0568
4,s1_severity_050,0.8638 ± 0.0280,0.8591 ± 0.0294,0.9022 ± 0.0303,0.8947 ± 0.0323,0.5904 ± 0.0194,0.5600 ± 0.0379

In [28]:
from experiments.analysis import get_results

df_loss_ss2 = get_results("../results/cv/loss", "s2")
df_loss_ss2

,name,overall_accuracy,overall_balanced_accuracy,stable_accuracy,stable_balanced_accuracy,converter_accuracy,converter_balanced_accuracy
0,s2_transition_300,0.8760 ± 0.0228,0.8719 ± 0.0221,0.9150 ± 0.0237,0.9078 ± 0.0251,0.5985 ± 0.0281,0.5726 ± 0.0591
1,s2_transition_200,0.8754 ± 0.0225,0.8722 ± 0.0182,0.9137 ± 0.0235,0.9086 ± 0.0210,0.6021 ± 0.0241,0.5822 ± 0.0462
2,s2_transition_700,0.8741 ± 0.0236,0.8706 ± 0.0237,0.9101 ± 0.0268,0.9038 ± 0.0280,0.6179 ± 0.0273,0.5913 ± 0.0385
3,s2_transition_050,0.8735 ± 0.0243,0.8677 ± 0.0223,0.9118 ± 0.0266,0.9038 ± 0.0267,0.6003 ± 0.0261,0.5686 ± 0.0478
4,s2_transition_075,0.8724 ± 0.0167,0.8683 ± 0.0126,0.9119 ± 0.0169,0.9045 ± 0.0135,0.5914 ± 0.0330,0.5640 ± 0.0525
5,s2_transition_000,0.8723 ± 0.0229,0.8694 ± 0.0207,0.9118 ± 0.0233,0.9058 ± 0.0224,0.5914 ± 0.0356,0.5691 ± 0.0417
6,s2_transition_1000,0.8721 ± 0.0271,0.8679 ± 0.0246,0.9094 ± 0.0273,0.9025 ± 0.0262,0.6060 ± 0.0356,0.5752 ± 0.0478
7,s2_transition_600,0.8719 ± 0.0238,0.8695 ± 0.0223,0.9076 ± 0.0239,0.9028 ± 0.0230,0.6179 ± 0.0465,0.5912 ± 0.0539
8,s2_transition_150,0.8712 ± 0.0258,0.8661 ± 0.0235,0.9083 ± 0.0257,0.9001 ± 0.0253,0.6070 ± 0.0422,0.5857 ± 0.0545
9,s2_transition_025,0.8701 ± 0.0247,0.8672 ± 0.0197,0.9094 ± 0.0245,0.9043 ± 0.0206,0.5896 ± 0.0351,0.5604 ± 0.0535
10,s2_transition_500,0.8694 ± 0.0283,0.8650 ± 0.0278,0.9055 ± 0.0281,0.8987 ± 0.0291,0.6126 ± 0.0453,0.5845 ± 0.0554
11,s2_transition_400,0.8691 ± 0.0194,0.8636 ± 0.0162,0.9060 ± 0.0198,0.8970 ± 0.0176,0.6059 ± 0.0391,0.5849 ± 0.0442
12,s2_transition_100,0.8523 ± 0.0699,0.8479 ± 0.0703,0.8891 ± 0.0725,0.8802 ± 0.0814,0.5893 ± 0.0585,0.5888 ± 0.0465

In [77]:
from experiments.analysis import get_results

df_loss_s3 = get_results("../results/cv/loss", "s3")
df_loss_s3

,name,overall_accuracy,overall_balanced_accuracy,stable_accuracy,stable_balanced_accuracy,converter_accuracy,converter_balanced_accuracy
0,s3_time_equal,0.8781 ± 0.0195,0.8734 ± 0.0195,0.9148 ± 0.0214,0.9078 ± 0.0213,0.6170 ± 0.0214,0.5842 ± 0.0420
1,s3_time_progressive,0.8765 ± 0.0252,0.8729 ± 0.0233,0.9129 ± 0.0244,0.9069 ± 0.0233,0.6175 ± 0.0400,0.5996 ± 0.0520
2,s3_time_progressive_mild,0.8701 ± 0.0242,0.8661 ± 0.0227,0.9057 ± 0.0270,0.8990 ± 0.0265,0.6162 ± 0.0305,0.5788 ± 0.0549
3,s3_time_late_focus_0_24,0.8541 ± 0.0299,0.8483 ± 0.0284,0.8915 ± 0.0300,0.8808 ± 0.0297,0.5872 ± 0.0439,0.5663 ± 0.0408

In [97]:
from experiments.analysis import get_results

df_loss_s4 = get_results("../results/cv/loss", "s4")
df_loss_s4

,name,overall_accuracy,overall_balanced_accuracy,stable_accuracy,stable_balanced_accuracy,converter_accuracy,converter_balanced_accuracy
0,s4_loss_mse,0.8773 ± 0.0188,0.8747 ± 0.0193,0.9115 ± 0.0203,0.9066 ± 0.0211,0.6340 ± 0.0326,0.5977 ± 0.0466
1,s4_loss_huber,0.8761 ± 0.0222,0.8718 ± 0.0201,0.9140 ± 0.0206,0.9069 ± 0.0204,0.6062 ± 0.0380,0.5778 ± 0.0528
2,s4_loss_mae,0.8729 ± 0.0246,0.8711 ± 0.0210,0.9164 ± 0.0258,0.9119 ± 0.0243,0.5627 ± 0.0199,0.5449 ± 0.0395